/**
    TEST
*/
export default {
    "0": "thunderstorm",
    "1": "thunderstorm",
    "2": "thunderstorm",
    "3": "thunderstorm",
    "4": "thunderstorm",
    "17": "thunderstorm",
    "35": "thunderstorm",
    "5": "rain_snow_mix",
    "6": "sleet_snow_mix",
    "7": "rain_snow_sleet_mix",
    "8": "icy",
    "9": "icy",
    "10": "rain_sleet_mix",
    "11": "light_rain",
    "12": "rain",
    "13": "light_snow",
    "14": "snow",
    "16": "snow",
    "42": "snow",
    "43": "snow",
    "15": "blizzard",
    "18": "rain_showers",
    "40": "rain_showers",
    "19": "dust",
    "20": "foggy",
    "21": "haze",
    "22": "smoke",
    "23": "windy",
    "24": "windy",
    "25": "frigid",
    "26": "cloudy",
    "27": "mostly_cloudy_night",
    "29": "mostly_cloudy_night",
    "33": "mostly_cloudy_night",
    "28": "mostly_cloudy",
    "30": "mostly_cloudy",
    "34": "mostly_cloudy",
    "31": "clear_night",
    "32": "clear",
    "36": "hot",
    "37": "scattered_thunderstorms",
    "38": "scattered_thunderstorms",
    "39": "scattered_rain_showers",
    "41": "scattered_snow_showers",
    "45": "scattered_rain_showers_night",
    "46": "scattered_snow_showers_night",
    "47": "scattered_thunderstorms_night"
};